# Generated by Django 4.2.1 on 2023-06-22 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apptaller', '0004_alter_contact_tipo_contacto'),
    ]

    operations = [
        migrations.AddField(
            model_name='atencion',
            name='aceptado',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
