# Generated by Django 4.2.1 on 2023-06-29 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apptaller', '0005_atencion_aceptado'),
    ]

    operations = [
        migrations.AddField(
            model_name='atencion',
            name='categoria',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
