# Generated by Django 4.2.1 on 2023-06-29 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apptaller', '0011_remove_atencion_usuario_atencion_mecanico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atencion',
            name='aceptado',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
