# Generated by Django 4.2.1 on 2023-07-12 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apptaller', '0012_alter_atencion_aceptado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Postulacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo', models.CharField(max_length=100)),
                ('foto', models.ImageField(default=' ', upload_to='')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('rut', models.CharField(max_length=10)),
                ('edad', models.IntegerField()),
                ('fecha_nacimiento', models.DateField()),
                ('direccion', models.CharField(max_length=50)),
                ('antecedentes_laborales', models.TextField(max_length=300)),
                ('antecedentes_academicos', models.TextField(max_length=300)),
            ],
        ),
    ]
