# Generated by Django 4.2.1 on 2023-07-13 03:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apptaller', '0014_atencion_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atencion',
            name='mecanico',
        ),
    ]
