# Generated by Django 4.2.1 on 2023-07-13 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apptaller', '0018_alter_mecanico_vigente'),
    ]

    operations = [
        migrations.AddField(
            model_name='postulacion',
            name='curriculum',
            field=models.FileField(default='', null=True, upload_to=''),
        ),
    ]
