# Generated by Django 4.2.1 on 2023-07-13 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apptaller', '0019_postulacion_curriculum'),
    ]

    operations = [
        migrations.AddField(
            model_name='mecanico',
            name='correo',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
