# Generated by Django 4.2.1 on 2023-07-13 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apptaller', '0020_mecanico_correo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mecanico',
            name='correo',
        ),
    ]
