# Generated by Django 4.2.1 on 2023-07-13 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apptaller', '0021_remove_mecanico_correo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mecanico',
            name='vigente',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
